"""drop tables

Revision ID: 18a34aabe899
Revises: 521dbcc6f6ff
Create Date: 2025-04-10 12:05:55.611199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a34aabe899'
down_revision: Union[str, None] = '521dbcc6f6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('tasks')
    op.drop_table('projects')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
