"""project|users|images upgrade

Revision ID: 1f50a373a600
Revises: b18985fb9e61
Create Date: 2025-05-18 15:07:38.325573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f50a373a600'
down_revision: Union[str, None] = 'b18985fb9e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_images')
    op.drop_constraint('projects_image_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'images', ['image_id'], ['id'])
    op.drop_constraint('users_image_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_image_id_fkey', 'users', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_image_id_fkey', 'projects', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_table('project_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='project_images_pkey'),
    sa.UniqueConstraint('filepath', name='project_images_filepath_key')
    )
    # ### end Alembic commands ###
