"""empty message

Revision ID: 2cb2d204abdd
Revises: 2f6fa9412880
Create Date: 2025-05-14 21:40:22.092210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb2d204abdd'
down_revision: Union[str, None] = '2f6fa9412880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_column('tasks', 'category_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category_color', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'category_id')
    # ### end Alembic commands ###
