"""ForeignKey category_name in projects

Revision ID: 39deba2f7e3b
Revises: cb4b09d88981
Create Date: 2025-05-14 19:32:07.548093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39deba2f7e3b'
down_revision: Union[str, None] = 'cb4b09d88981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('projects_category_name_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_category_name_fkey', 'projects', 'categories', ['category_name'], ['name'], ondelete='CASCADE')
    op.drop_column('projects', 'category_id')
    # ### end Alembic commands ###
