"""update users, create images

Revision ID: 442bdbab970d
Revises: 66d6e3c5d2e0
Create Date: 2025-05-12 15:46:09.111351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442bdbab970d'
down_revision: Union[str, None] = '66d6e3c5d2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_image_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_image_id_fkey', 'users', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
