"""delete all

Revision ID: 547d607b0be5
Revises: e0f8c68ea77b
Create Date: 2025-05-12 14:44:28.692773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547d607b0be5'
down_revision: Union[str, None] = 'e0f8c68ea77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_table('tasks')
    op.drop_table('project_users')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'image_id')
    op.drop_table('images')
    # ### end Alembic commands ###
