"""delete projects/users

Revision ID: 6f9fc97385ca
Revises: 9891e5ef9730
Create Date: 2025-05-07 22:19:36.630687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9fc97385ca'
down_revision: Union[str, None] = '9891e5ef9730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_users")
    op.drop_table("tasks")
    op.drop_table("projects")
    op.drop_table("users")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
