"""projects - icon

Revision ID: 7c96f99a602f
Revises: 364e65383c2a
Create Date: 2025-05-15 01:23:06.718707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c96f99a602f'
down_revision: Union[str, None] = '364e65383c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.drop_table('projectimages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectimages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='projectimages_pkey'),
    sa.UniqueConstraint('filepath', name='projectimages_filepath_key')
    )
    op.drop_table('project_images')
    # ### end Alembic commands ###
