"""substicles

Revision ID: 7ca7fd22fe5d
Revises: 2cb2d204abdd
Create Date: 2025-05-14 22:05:44.797817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca7fd22fe5d'
down_revision: Union[str, None] = '2cb2d204abdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('importance_color', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'importance_color')
    # ### end Alembic commands ###
