"""tasks and substacles

Revision ID: a1cfbe6c0d6c
Revises: b680d056a505
Create Date: 2025-05-15 00:06:54.835569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cfbe6c0d6c'
down_revision: Union[str, None] = 'b680d056a505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substacles', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_completed')
    op.drop_column('substacles', 'is_completed')
    # ### end Alembic commands ###
