"""perfomer->performer

Revision ID: be3a49ef36fe
Revises: 2530cb285972
Create Date: 2025-04-13 23:54:13.245404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3a49ef36fe'
down_revision: Union[str, None] = '2530cb285972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('performer', sa.String(), nullable=True))
    op.drop_column('tasks', 'perfomer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('perfomer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'performer')
    # ### end Alembic commands ###
