"""ForeignKey category_name in projects

Revision ID: cb4b09d88981
Revises: db2f5c1ecb38
Create Date: 2025-05-14 19:23:10.061216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4b09d88981'
down_revision: Union[str, None] = 'db2f5c1ecb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'projects', 'categories', ['category_name'], ['name'], ondelete='CASCADE')
    op.drop_column('projects', 'category_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category_color', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'category_name')
    # ### end Alembic commands ###
